// iosHelp.js — Context-sensitive help system

export function getHelp(state) {
  const helps = {
    user: [
      ["enable", "Turn on privileged commands"],
      ["exit", "Exit from the EXEC"],
      ["ping", "Send echo messages"],
      ["show", "Show running system information"],
      ["traceroute", "Trace route to destination"],
    ],
    privileged: [
      ["clear", "Reset functions"],
      ["clock set", "Set the time and date"],
      ["configure terminal", "Enter configuration mode"],
      ["copy", "Copy from one file to another"],
      ["crypto key generate rsa", "Generate RSA keys for SSH"],
      ["debug", "Debugging functions"],
      ["exit", "Exit from the EXEC"],
      ["ping", "Send echo messages"],
      ["reload", "Halt and perform a cold restart"],
      ["show", "Show running system information"],
      ["ssh", "Open a secure shell client connection"],
      ["terminal", "Set terminal line parameters"],
      ["traceroute", "Trace route to destination"],
      ["undebug", "Disable debugging functions"],
      ["write memory", "Save running config to NVRAM"],
    ],
    config: [
      ["cdp run", "Enable CDP"],
      ["crypto key generate rsa", "Generate RSA keys"],
      ["exit", "Exit from configure mode"],
      ["hostname", "Set system's network name"],
      ["interface", "Select an interface to configure"],
      ["ip access-list", "Named access list"],
      ["ip arp inspection", "Dynamic ARP Inspection"],
      ["ip dhcp excluded-address", "Prevent DHCP from assigning certain addresses"],
      ["ip dhcp pool", "Configure DHCP address pool"],
      ["ip dhcp snooping", "DHCP Snooping"],
      ["ip domain-name", "Define the default domain name"],
      ["ip nat", "NAT configuration commands"],
      ["ip route", "Establish static routes"],
      ["ipv6 route", "Establish IPv6 static routes"],
      ["ipv6 unicast-routing", "Enable IPv6 routing"],
      ["line", "Configure a terminal line"],
      ["lldp run", "Enable LLDP"],
      ["no", "Negate a command or set its defaults"],
      ["ntp", "Configure NTP"],
      ["router", "Enable a routing process"],
      ["spanning-tree", "Spanning Tree Subsystem"],
      ["username", "Establish user name authentication"],
      ["vlan", "VLAN commands"],
    ],
    "config-if": [
      ["cdp enable", "Enable CDP on this interface"],
      ["channel-group", "Etherchannel/port bundling"],
      ["description", "Interface specific description"],
      ["exit", "Exit from interface configuration mode"],
      ["ip address", "Set the IP address of an interface"],
      ["ip dhcp snooping trust", "DHCP Snooping trust"],
      ["ip nat inside|outside", "NAT interface designation"],
      ["ip ospf", "OSPF interface commands"],
      ["ipv6 address", "Set the IPv6 address"],
      ["lldp transmit|receive", "LLDP per-interface"],
      ["no", "Negate a command"],
      ["shutdown", "Shutdown the selected interface"],
      ["spanning-tree bpduguard", "Don't accept BPDUs on this interface"],
      ["spanning-tree portfast", "Portfast on this interface"],
      ["switchport access vlan", "Set access mode VLAN"],
      ["switchport mode", "Set interface trunking mode (access|trunk)"],
      ["switchport nonegotiate", "Disable DTP negotiation"],
      ["switchport port-security", "Port security commands"],
      ["switchport trunk", "Trunk configuration"],
      ["switchport voice vlan", "Set voice VLAN"],
    ],
    "config-line": [
      ["exec-timeout", "Set the EXEC timeout"],
      ["exit", "Exit from line configuration mode"],
      ["login local", "Enable login using local database"],
      ["password", "Set a line password"],
      ["transport input", "Define which protocols to use for incoming connections"],
    ],
    "config-router": [
      ["exit", "Exit from router configuration mode"],
      ["log-adjacency-changes", "Log changes in adjacency state"],
      ["network", "Enable routing on an IP network"],
      ["passive-interface", "Suppress routing updates on an interface"],
      ["redistribute", "Redistribute information from another routing protocol"],
      ["router-id", "Router ID for this OSPF process"],
    ],
    "config-vlan": [
      ["exit", "Exit from VLAN configuration mode"],
      ["name", "ASCII name of the VLAN"],
    ],
    "config-acl": [
      ["deny", "Specify packets to reject"],
      ["exit", "Exit from access-list configuration mode"],
      ["permit", "Specify packets to forward"],
      ["remark", "Access list entry comment"],
    ],
    "config-ext-acl": [
      ["deny", "Specify packets to reject"],
      ["exit", "Exit from access-list configuration mode"],
      ["permit", "Specify packets to forward"],
      ["remark", "Access list entry comment"],
    ],
    "config-dhcp": [
      ["default-router", "Default routers"],
      ["dns-server", "DNS servers"],
      ["exit", "Exit from DHCP pool configuration mode"],
      ["network", "Network number and mask"],
    ],
  };
  const entries = helps[state.mode] || [["?", "Show help"]];
  return entries.map(([cmd, desc]) => `  ${cmd.padEnd(30)} ${desc}`).join("\n");
}

